#!/usr/bin/env node
/* settings-pages.test.js — guard the toolbar popup and the options page.
 *
 * Both pages are generated by build.js. The DOM contract below is what the
 * page scripts and tools/verify-ui.js address by id, so a template edit that
 * drops one breaks a button silently. The behaviour checks run the real
 * options.js against a stubbed chrome API and a recording IndexedDB vault,
 * because the two bugs they pin were label/behaviour mismatches that no
 * screenshot shows: "export backup" downloading the Chrome Sync blob instead
 * of the local vault, and "delete backup" claiming to clear the REST copy.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const EXT = path.join(ROOT, 'extension');

let passed = 0;
let failed = 0;
const check = (name, ok, detail) => {
  if (ok) { passed += 1; console.log('ok   ' + name); } else {
    failed += 1;
    console.log('FAIL ' + name + (detail ? ' — ' + detail : ''));
  }
};

execFileSync(process.execPath, [path.join(ROOT, 'build.js')], { cwd: ROOT, stdio: 'pipe' });
const read = (f) => fs.readFileSync(path.join(EXT, f), 'utf8');
const popupHtml = read('popup.html');
const optionsHtml = read('options.html');
const optionsJs = read('options.js');
const popupJs = read('popup.js');

const ids = (html) => new Set([...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));
const dupes = (html) => {
  const seen = new Map();
  for (const m of html.matchAll(/\sid="([^"]+)"/g)) seen.set(m[1], (seen.get(m[1]) || 0) + 1);
  return [...seen].filter(([, n]) => n > 1).map(([id]) => id);
};

/* ── popup contract ─────────────────────────────────────────────────────── */
const popIds = ids(popupHtml);
const popWanted = ['k', 'foot', 'backup', 'backup-text', 'open-app', 'open-drawer', 'open-redeem', 'copy-share', 'open-options'];
check('popup keeps every id its script and verify-ui address',
  popWanted.every((id) => popIds.has(id)), popWanted.filter((id) => !popIds.has(id)).join(','));
check('popup has no duplicate ids', dupes(popupHtml).length === 0, dupes(popupHtml).join(','));
check('popup has exactly one primary action',
  (popupHtml.match(/class="act primary/g) || []).length === 1);
check('popup buttons declare type="button"',
  [...popupHtml.matchAll(/<button\b[^>]*>/g)].every((m) => /type="button"/.test(m[0])));
check('popup script addresses only ids that exist',
  [...popupJs.matchAll(/\$\('([\w-]+)'\)/g)].every((m) => popIds.has(m[1])),
  [...popupJs.matchAll(/\$\('([\w-]+)'\)/g)].map((m) => m[1]).filter((id) => !popIds.has(id)).join(','));

/* ── options contract ───────────────────────────────────────────────────── */
const optIds = ids(optionsHtml);
const optWanted = ['enabled', 'cfg', 'rest-only', 'endpoint', 'token', 'auto', 'save', 'test', 'status', 'dirty',
  'sync-badge', 'sync-state', 'sync-meta', 'export', 'export-csv', 'status2', 'wipe', 'status3',
  'st-gift', 'st-preset', 'st-untried', 'st-share', 'community', 'backup', 'local', 'danger'];
check('options keeps every id its script addresses',
  optWanted.every((id) => optIds.has(id)), optWanted.filter((id) => !optIds.has(id)).join(','));
check('options has no duplicate ids', dupes(optionsHtml).length === 0, dupes(optionsHtml).join(','));
check('options script addresses only ids that exist',
  [...optionsJs.matchAll(/\$\('([\w-]+)'\)/g)].every((m) => optIds.has(m[1])),
  [...optionsJs.matchAll(/\$\('([\w-]+)'\)/g)].map((m) => m[1]).filter((id) => !optIds.has(id)).join(','));
check('options nav links point at real sections',
  [...optionsHtml.matchAll(/<a href="#([\w-]+)"/g)].every((m) => optIds.has(m[1])));
check('options offers both backup destinations as radios',
  /type="radio" name="backend" value="chrome-sync"/.test(optionsHtml) && /type="radio" name="backend" value="rest"/.test(optionsHtml));
check('the destructive action lives only in the danger section',
  /<section class="block danger" id="danger"[\s\S]*id="wipe"/.test(optionsHtml)
  && !/id="wipe"[\s\S]*<section class="block"/.test(optionsHtml));
check('wipe copy says the REST copy is NOT deleted',
  /REST endpoint không bị xoá/.test(optionsHtml) && !/Xoá bản sao lưu trên cloud/.test(optionsHtml));
check('options never renders the token value back into the page',
  !/\.value\s*=\s*settings\.token/.test(optionsJs) && /hasToken/.test(optionsJs));

/* ── options behaviour against stubs ───────────────────────────────────── */
function el(id) {
  const listeners = {};
  let text = '';
  return {
    id, hidden: false, disabled: false, checked: false, value: '', placeholder: '', className: '',
    dataset: {}, title: '', children: [],
    /* As in the DOM, assigning textContent replaces every child node. */
    get textContent() { return text; },
    set textContent(value) { text = value; this.children = []; },
    addEventListener(type, fn) { (listeners[type] = listeners[type] || []).push(fn); },
    async fire(type) { for (const fn of listeners[type] || []) await fn({ preventDefault() {} }); },
    appendChild(child) { this.children.push(child); return child; },
    setAttribute(k, v) { this[k] = v; }, getAttribute(k) { return this[k]; }, removeAttribute(k) { delete this[k]; },
    focus() { this.focused = true; }, click() { this.clicked = true; }, remove() {},
    querySelector() { return null; }, getBoundingClientRect() { return { top: 0 }; },
  };
}

async function runOptions(settings, vaultRows, initialStatus) {
  const nodes = new Map([...optIds].map((id) => [id, el(id)]));
  const radios = ['chrome-sync', 'rest'].map((value) => Object.assign(el('radio-' + value), { value }));
  const downloads = [];
  const asked = [];
  let status = initialStatus || { state: 'ok', lastSyncAt: '2026-10-02T03:04:00.000Z', recordCount: 7 };
  const tick = () => new Promise((r) => setImmediate(r));
  const document = {
    documentElement: { scrollHeight: 1000 },
    body: { appendChild(a) { downloads.push(a); } },
    getElementById: (id) => nodes.get(id) || null,
    querySelector: (sel) => (sel === 'input[name="backend"]:checked' ? radios.find((r) => r.checked) || null : null),
    querySelectorAll: (sel) => (sel === 'input[name="backend"]' ? radios : []),
    createElement: (tag) => Object.assign(el(tag), { tagName: tag }),
  };
  const chrome = {
    runtime: {
      async sendMessage(msg) {
        asked.push(msg.op);
        if (msg.op === 'getSettings') return settings;
        if (msg.op === 'status') return status;
        if (msg.op === 'setSettings') {
          /* Mirrors the worker: a new destination drops the old status. */
          const moved = msg.payload.backend !== settings.backend || msg.payload.endpoint !== settings.endpoint || Boolean(msg.payload.token);
          Object.assign(settings, msg.payload, { hasToken: Boolean(msg.payload.token) || settings.hasToken });
          if (moved) status = { state: 'never-synced', lastSyncAt: null, error: null };
          return { ok: true, moved };
        }
        if (msg.op === 'wipe') return { ok: true };
        if (msg.op === 'export') throw new Error('options must not export the Chrome Sync blob');
        return { ok: false, error: 'unexpected ' + msg.op };
      },
    },
    storage: { onChanged: { addListener() {} } },
  };
  const blobs = [];
  class Vault {
    async init() { return this; }
    async all() { return vaultRows; }
    async exportJSON() { return JSON.stringify({ version: 1, codes: vaultRows }); }
    async exportCSV() { return 'code\n' + vaultRows.map((r) => r.code).join('\n'); }
  }
  const window = {
    innerHeight: 900, scrollY: 0,
    addEventListener() {},
    DFRedeemVault: { Vault, IndexedDBAdapter: function IndexedDBAdapter() {} },
  };
  /* Strip the inlined schema/vault modules: the stub vault above replaces
   * them, and they would otherwise try to open a real IndexedDB. */
  const MODULE_END = /\n\}\(typeof window !== 'undefined' \? window : globalThis\)\);\n/;
  const strip = (text, name) => {
    const start = text.indexOf('var ' + name + ' = (function');
    if (start < 0) throw new Error(name + ' module not found in options.js');
    const end = text.slice(start).search(MODULE_END);
    if (end < 0) throw new Error(name + ' module end not found');
    return text.slice(0, start) + text.slice(start + end).replace(MODULE_END, '\n');
  };
  const src = strip(strip(optionsJs, 'DFRedeemSchema'), 'DFRedeemVault');
  const ctx = {
    window, document, chrome, console, setTimeout, clearTimeout, setImmediate, requestAnimationFrame: (fn) => setImmediate(fn),
    Blob: function Blob(parts, opts) { blobs.push({ text: parts.join(''), type: opts && opts.type }); },
    URL: Object.assign(function URL(u) { const x = new globalThis.URL(u); return x; }, {
      createObjectURL: () => 'blob:test', revokeObjectURL() {},
    }),
    confirm: () => true, Event: function Event(type) { this.type = type; },
  };
  ctx.globalThis = ctx;
  vm.createContext(ctx);
  vm.runInContext(src, ctx, { filename: 'options.js' });
  for (let i = 0; i < 20; i += 1) await tick();
  return { nodes, radios, downloads, blobs, asked, tick, settings };
}

(async () => {
  const rows = [
    { code: 'GIFT1', kind: 'giftcode', status: 'untried' },
    { code: 'GIFT2', kind: 'giftcode', status: 'success' },
    { code: 'GIFT3', kind: 'giftcode', status: 'mine' },
    { code: 'PRE1', kind: 'preset', status: 'untried' },
  ];

  const off = await runOptions({ enabled: false, backend: 'chrome-sync', endpoint: '', autoSync: false, hasToken: false }, rows);
  check('backup off: configuration and test are hidden', off.nodes.get('cfg').hidden === true && off.nodes.get('test').hidden === true);
  check('backup off: badge says off, not a stale sync state', off.nodes.get('sync-badge').dataset.state === 'off');
  check('local stats count gifts and presets separately',
    off.nodes.get('st-gift').textContent === 3 && off.nodes.get('st-preset').textContent === 1
    && off.nodes.get('st-untried').textContent === 1 && off.nodes.get('st-share').textContent === 2,
    ['st-gift', 'st-preset', 'st-untried', 'st-share'].map((id) => off.nodes.get(id).textContent).join('/'));

  await off.nodes.get('export').fire('click');
  for (let i = 0; i < 10; i += 1) await off.tick();
  const json = off.blobs.find((b) => b.type === 'application/json');
  check('export downloads the LOCAL vault, never the Chrome Sync blob',
    json && JSON.parse(json.text).codes.length === rows.length && !off.asked.includes('export'),
    json ? json.text.slice(0, 80) : 'no json blob; asked=' + off.asked.join(','));
  check('export file name is dated', off.downloads.some((a) => /^df-redeem-kho-\d{4}-\d{2}-\d{2}\.json$/.test(a.download)));
  await off.nodes.get('export-csv').fire('click');
  for (let i = 0; i < 10; i += 1) await off.tick();
  check('CSV export is offered from the same local vault', off.blobs.some((b) => /^code\n/.test(b.text)));

  const on = await runOptions({ enabled: true, backend: 'rest', endpoint: 'https://vault.test/api', autoSync: true, hasToken: true }, rows);
  check('backup on: configuration visible and REST fields shown',
    on.nodes.get('cfg').hidden === false && on.nodes.get('rest-only').hidden === false);
  check('saved token is signalled by placeholder, never echoed',
    on.nodes.get('token').value === '' && /Đã lưu token/.test(on.nodes.get('token').placeholder));
  check('backup on: badge shows the last sync state', on.nodes.get('sync-badge').dataset.state === 'ok');
  check('sync meta lists last time and record count', on.nodes.get('sync-meta').children.length === 2);

  on.nodes.get('endpoint').value = 'ftp://nope';
  await on.nodes.get('endpoint').fire('input');
  check('editing marks the form dirty', on.nodes.get('dirty').hidden === false);
  const before = on.asked.length;
  await on.nodes.get('save').fire('click');
  check('an invalid endpoint is rejected before it reaches the worker',
    !on.asked.slice(before).includes('setSettings') && on.nodes.get('status').dataset.tone === 'err');

  on.nodes.get('endpoint').value = 'https://vault.test/v2';
  await on.nodes.get('endpoint').fire('input');
  await on.nodes.get('test').fire('click');
  for (let i = 0; i < 10; i += 1) await on.tick();
  const tail = on.asked.slice(before);
  check('test saves unsaved edits first, then tests the stored settings',
    tail.indexOf('setSettings') !== -1 && tail.indexOf('test') > tail.indexOf('setSettings'), tail.join(','));
  check('saved endpoint is the edited one', on.settings.endpoint === 'https://vault.test/v2', on.settings.endpoint);

  const broken = await runOptions({ enabled: true, backend: 'rest', endpoint: 'https://old.test/api', autoSync: true, hasToken: false }, rows,
    { state: 'error', lastSyncAt: null, error: 'Lỗi mạng: không kết nối được máy chủ (mất Internet, sai địa chỉ hoặc máy chủ chặn truy cập).' });
  check('a failed backup shows the Vietnamese error on the badge',
    broken.nodes.get('sync-badge').dataset.state === 'error' && /Lỗi mạng/.test(JSON.stringify(broken.nodes.get('sync-meta').children.map((c) => c.textContent))));
  broken.nodes.get('endpoint').value = 'https://new.test/api';
  await broken.nodes.get('endpoint').fire('input');
  await broken.nodes.get('save').fire('click');
  for (let i = 0; i < 10; i += 1) await broken.tick();
  check('saving a new destination clears the old error from the badge',
    broken.nodes.get('sync-badge').dataset.state === 'never-synced' && broken.nodes.get('sync-meta').children.length === 0,
    broken.nodes.get('sync-badge').dataset.state);
  check('saving a new destination says the old status was cleared',
    /xoá trạng thái cũ/.test(broken.nodes.get('status').textContent) && broken.nodes.get('status').dataset.tone === 'ok',
    broken.nodes.get('status').textContent);

  await on.nodes.get('wipe').fire('click');
  for (let i = 0; i < 10; i += 1) await on.tick();
  check('wipe asks the worker and reports success', on.asked.includes('wipe') && on.nodes.get('status3').dataset.tone === 'ok');

  console.log(`${passed} passed, ${failed} failed, ${passed + failed} total`);
  process.exit(failed ? 1 : 0);
})().catch((err) => {
  console.log('FAIL settings page harness — ' + (err && err.stack || err));
  console.log(`${passed} passed, ${failed + 1} failed, ${passed + failed + 1} total`);
  process.exit(1);
});
